[versions]
ksp = "1.9.22-1.0.17"
androidx-core = "1.12.0"
compose-bom = "2024.02.00"
activity-compose = "1.8.2"
androidx-lifecycle = "2.7.0"
androidx-room = "2.6.1"
hilt = "2.49"
hilt_navigation_compose = "1.1.0"
androidx-navigation = "2.7.7"
timber = "5.0.1"
firebaseBom = "32.7.1"
nav-version = '2.7.7'
swipe = "1.2.0"
accompanist_pager = "0.25.1"
accompanist_pager_indicators = "0.19.0"
accompanist_permissions = '0.34.0'
lottie_compose = "6.1.0"
junit = "4.13.2"
junit-test = "3.5.1"
espresso_core = "3.5.1"
agp = "8.2.2"
kotlin = "1.9.22"
google-services = "4.4.0"
firebase-crashlytics-plugin="2.9.9"
material3Android = "1.2.0"

[libraries]
#core
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }

#compose
androidx-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }

ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "nav-version" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie_compose" }

#room
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }

#hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt_navigation_compose" }

#navigation
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidx-navigation" }

#timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

#lifecycle
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }

#firebase
firebaseBom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebaseMessaging = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
firebaseAnalytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebaseCrashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }

#swipe
swipe = { group = "me.saket.swipe", name = "swipe", version.ref = "swipe" }

#accompanist
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist_pager" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist_pager_indicators" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist_permissions" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist_permissions" }

#junit
junit = { group = "junit", name = "junit", version.ref = "junit" }

#test
androidx-test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "junit-test" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso_core" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "espresso_core" }

[bundles]
compose = ["androidx-compose-activity", "androidx-material3-android", "lifecycle-runtime-compose",
    "lifecycle-viewmodel-compose","androidx-navigation","lottie-compose"]
room = ["androidx-room-runtime", "androidx-room-ktx"]
hilt = ["hilt-android", "hilt-navigation-compose"]
navigation = ["androidx-navigation-fragment", "androidx-navigation-ui"]
lifecycle = ["androidx-lifecycle-livedata", "androidx-lifecycle-runtime", "androidx-lifecycle-viewmodel"]
firebase = ["firebaseMessaging", "firebaseAnalytics", "firebaseCrashlytics"]
accompanist = ["accompanist-pager", "accompanist-pager-indicators", "accompanist-permissions","accompanist-systemuicontroller"]
test = ["androidx-test-ext","androidx-test-espresso","androidx-compose-ui-test"]


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlin"  }
firebase-crashlytics = { id = "com.google.firebase.crashlytics",  version.ref = "firebase-crashlytics-plugin"  }
